## Oppstartceller

#### Boot cell

Skip if `module_update.py` is in same folder as notebook, next cell downloads this file which in turn will download other files.

In [2]:
!curl -s "https://raw.githubusercontent.com/Yoonsen/Modules/master/module_update.py" > "module_update.py"

#### Get essentials

Import text and graph modules for analysis, and css for display

In [3]:
from module_update import update, css, code_toggle

In [4]:
css()

### Import modules, maybe update with overwrite=True

In [5]:
update('graph_networkx_louvain')
import nbtext as nb
import graph_networkx_louvain as gnl
from graph_networkx_louvain import cutdown, make_collocation_graph
from random import sample
%matplotlib inline

Updated file `D:\Documents\GitHub\Seminar-Mai-2019\graph_networkx_louvain.py`

## Tråling i et definert korpus

Finner bøker som inneholder varianter av ord, og sammenligner. 


Starter med å definere et korpus

In [15]:
korpus = nb.book_urn(words='arbeid', ddk="3%", period=(1960, 1970), limit=1000)

In [16]:
len(korpus)

1000

Dernest kommer settet det skal tråles med.

In [21]:
wb = {'Kvinne': [
    'kvinne', 'kvinner', 'kvinnene'
],
     'Frihet':['frihet', 'grenser', 'fengsel'],
      
     'Lønn':['godtgjørelse', 'kapital', 'lønn', 'lønna', 'lønnen']}

Selve trålingen gjøres med kommandoen `wordbag_eval`

In [22]:
trål = nb.wordbag_eval(wb, korpus)

Se på resultatene. De er sortert etter snittverdienm

In [23]:
trål

               Frihet  Kvinne   Lønn       snitt
2007051000056    29.0  1276.0    6.0  437.000000
2013041608058     3.0   512.0   12.0  175.666667
2007061500005     8.0   454.0    1.0  154.333333
2014071606072     5.0    12.0  427.0  148.000000
2007052401046     3.0   346.0    1.0  116.666667
2007080201114     4.0   320.0   14.0  112.666667
2016110148065    23.0     5.0  300.0  109.333333
2008052000057    26.0     8.0  282.0  105.333333
2011102408043     0.0   303.0    0.0  101.000000
2016072948097    23.0     2.0  274.0   99.666667
2007043004066     6.0     3.0  253.0   87.333333
2007041701039     4.0   257.0    0.0   87.000000
2007052304042     0.0   256.0    1.0   85.666667
2007042401123     0.0     4.0  232.0   78.666667
2010110506067   224.0     0.0    3.0   75.666667
2007050804038    11.0   159.0   50.0   73.333333
2007080201029    29.0    45.0  133.0   69.000000
2007050901032    30.0    42.0  133.0   68.333333
2010110905074    30.0   153.0   18.0   67.000000
2012061108122     6.0   141.0   49.0   65.333333
2007052501010    12.0   154.0   17.0   61.000000
2007041001004     6.0     6.0  168.0   60.000000
2016021608115     0.0   165.0    0.0   55.000000
2007031501050    10.0   113.0   42.0   55.000000
2007032001024    12.0   145.0    7.0   54.666667
2007052104092     2.0     0.0  160.0   54.000000
2007073004050   140.0    17.0    3.0   53.333333
2012020808130   138.0    10.0    9.0   52.333333
2012010508023    19.0     6.0  132.0   52.333333
2007073001091   147.0     5.0    3.0   51.666667
...               ...     ...    ...         ...
2012083008225     0.0     0.0    1.0    0.333333
2012083008224     1.0     0.0    0.0    0.333333
2011022305081     0.0     0.0    1.0    0.333333
2011020206001     1.0     0.0    0.0    0.333333
2014020548051     0.0     1.0    0.0    0.333333
2011011806006     1.0     0.0    0.0    0.333333
2016020508182     0.0     0.0    1.0    0.333333
2007050801073     1.0     0.0    0.0    0.333333
2007051001003     1.0     0.0    0.0    0.333333
2015062908102     1.0     0.0    0.0    0.333333
2007052201059     1.0     0.0    0.0    0.333333
2007052500047     1.0     0.0    0.0    0.333333
2007072400043     1.0     0.0    0.0    0.333333
2007073100038     0.0     0.0    1.0    0.333333
2008051604098     0.0     0.0    1.0    0.333333
2012073108050     0.0     0.0    1.0    0.333333
2014072908131     0.0     0.0    1.0    0.333333
2014061606048     1.0     0.0    0.0    0.333333
2014061205080     0.0     0.0    1.0    0.333333
2014060208099     1.0     0.0    0.0    0.333333
2014051408282     0.0     1.0    0.0    0.333333
2010110405005     1.0     0.0    0.0    0.333333
2010111605036     1.0     0.0    0.0    0.333333
2010111706093     0.0     0.0    1.0    0.333333
2014031208028     0.0     0.0    1.0    0.333333
2011011006059     0.0     1.0    0.0    0.333333
2014022808140     0.0     0.0    1.0    0.333333
2011011106088     0.0     0.0    1.0    0.333333
2011011206026     1.0     0.0    0.0    0.333333
2008052000040     0.0     0.0    1.0    0.333333

[830 rows x 4 columns]

For å begrense kan det lages forskjellige kommandoer. Eksempler

In [35]:
# Se på der hvor verdien er større enn en gitt verdi

trål[(trål['Kvinne'] > 100) & (trål['Frihet'] > 10) & (trål['Lønn'] > 4)]

               Frihet  Kvinne  Lønn       snitt
2007051000056    29.0  1276.0   6.0  437.000000
2007050804038    11.0   159.0  50.0   73.333333
2010110905074    30.0   153.0  18.0   67.000000
2007052501010    12.0   154.0  17.0   61.000000
2007032001024    12.0   145.0   7.0   54.666667

Resultatet kan legges i en variabel

In [36]:
fangst = trål[(trål['Kvinne'] > 100) & (trål['Frihet'] > 10) & (trål['Lønn'] > 4)]

Og metadata kan hentes ut

In [38]:
nb.frame(nb.metadata(list(fangst.index)))

,0,1,2,3,4,5,6,7,8,9
0,2007051000056,"Friedan, Betty",1967,Myten om kvinnen,,Universitetsforlaget,notfiction,b3b0e41deae0c49298a5d2e00389b9a5,nob,eng
1,2007050804038,,1964,Det Norske Storting gjennom 150 år,,I kommisjon hos Gyldendal;Oslo : I kommisjon h...,notfiction,ff8e65e91c00cbd3b530c702dd32e889,nob,
2,2010110905074,"Strøm, Axel",1963,Lærebok i sosialmedisin,,Fabritius,notfiction,52fe273a5bac6af338a13e87f57b10f8,mul,
3,2007052501010,,1967,Familiepolitikk i dag og i morgen,,,notfiction,224c39f2806657518ed05a1515891c96,nob,
4,2007032001024,,1960,Skikk og bruk,,Cappelen,notfiction,a77760f3bb5df5841c97deecb0a0b178,nob,